from datetime import datetime
from typing import Protocol

from app.domain.entities.enums import ApplicationStatus
from app.domain.entities.records import Application
from app.domain.repositories.entity import EntityRepository


class ApplicationRepository(EntityRepository[Application], Protocol):
    def count(self) -> int: ...

    def creation_dates(self) -> list[datetime]: ...

    def status_rows(self) -> list[tuple[ApplicationStatus]]: ...

    def count_recommended(self) -> int: ...

    def find_for_user_job(self, user_id: int, job_id: int) -> Application | None: ...

    def for_user(self, user_id: int) -> list[Application]: ...

    def for_job(self, job_id: int) -> list[Application]: ...

    def mark_submitted_seen(self, job_id: int) -> int: ...

    def find_for_candidate_company(
        self, candidate_id: int, company_id: int
    ) -> Application | None: ...

    def candidate_ids(self, job_id: int) -> list[tuple[int]]: ...
