export const JOB_SECTORS = [
  "Alimentos y bebidas",
  "Tecnologia y software",
  "Analitica y ciencia de datos",
  "Inteligencia artificial",
  "Finanzas y banca",
  "Salud y bienestar",
  "Educacion",
  "Marketing y publicidad",
  "Ventas y comercio",
  "Recursos humanos",
  "Legal",
  "Logistica y transporte",
  "Manufactura",
  "Construccion e ingenieria",
  "Energia y servicios publicos",
  "Telecomunicaciones",
  "Turismo y hoteleria",
  "Retail y consumo masivo",
  "Medios y entretenimiento",
  "Agricultura y medio ambiente",
  "Sector publico y social",
].sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }));
